### ISSUE TITLE
`glxtest:` libEGL no display. EGL test failed

### ISSUE THREAD

**Issue by pc00per** [elFarto/nvidia-vaapi-driver#115]
```
$[~]$ NVD_LOG=1 firefox
[GFX1-]: glxtest: libEGL no display
[GFX1-]: glxtest: EGL test failed
[GFX1-]: Failed[3] to create EGL library  display: FEATURE_FAILURE_NO_DISPLAY
[GFX1-]: Failed[3] to create EGL library  display: FEATURE_FAILURE_NO_DISPLAY
[GFX1-]: Failed GL context creation for hardware WebRender: true
[GFX1-]: Failed[3] to create EGL library  display: FEATURE_FAILURE_NO_DISPLAY
[GFX1-]: Failed[3] to create EGL library  display: FEATURE_FAILURE_NO_DISPLAY
[GFX1-]: Failed GL context creation for hardware WebRender: true
[GFX1-]: Failed[3] to create EGL library  display: FEATURE_FAILURE_NO_DISPLAY
[GFX1-]: Failed[3] to create EGL library  display: FEATURE_FAILURE_NO_DISPLAY
[GFX1-]: Failed GL context creation for hardware WebRender: true
[GFX1-]: Failed[3] to create EGL library  display: FEATURE_FAILURE_NO_DISPLAY
[GFX1-]: Failed[3] to create EGL library  display: FEATURE_FAILURE_NO_DISPLAY
[GFX1-]: Failed GL context creation for hardware WebRender: true
[GFX1-]: Failed[3] to create EGL library  display: FEATURE_FAILURE_NO_DISPLAY
[GFX1-]: Failed[3] to create EGL library  display: FEATURE_FAILURE_NO_DISPLAY
[GFX1-]: Failed GL context creation for WebRender: 0
[GFX1-]: FEATURE_FAILURE_WEBRENDER_INITIALIZE_UNSPECIFIED(Create)
[GFX1-]: Failed to connect WebRenderBridgeChild. isParent=true
[GFX1-]: Fallback WR to SW-WR
Missing chrome or resource URL: resource://gre/modules/UpdateListener.sys.mjs
```
Happens on Wayland. No issues on X11.

**Comment by pc00per** [comment]
Okay. Fixed by `EGL_PLATFORM=wayland`. Ignore this issue.

**Comment by UnsaltedScholar** [comment]
Hello, I am still seeing this issue on Firefox v127.0.1. I suppose it should be noted that I am running an Optimus system on Wayland using an nvidia-470xx-dkms driver in case that is at all relevant. The dGPU is also quite old (Quadro K1100m) and only supports hardware decoding of H264 so I'm not all too sure if this is even addressable.

**Comment by satmandu** [comment]
I also see the same issue as @UnsaltedScholar. If there's a solution for using the Nvidia 470 driver with Wayland, I'd love to see it. (This is on Gnome 48 on ubutu 25.04.)

This is the command line to replicate the issue:
```bash
MOZ_X11_EGL=1 EGL_PLATFORM=wayland __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/10_nvidia.json MOZ_ENABLE_WAYLAND=1 firefox
[GFX1-]: glxtest: libEGL no display
[GFX1-]: glxtest: EGL test failed
[GFX1-]: Failed[3] to create EGL library  display: FEATURE_FAILURE_NO_DISPLAY
[GFX1-]: Failed[3] to create EGL library  display: FEATURE_FAILURE_NO_DISPLAY
[GFX1-]: Failed GL context creation for hardware WebRender: true
[GFX1-]: Failed[3] to create EGL library  display: FEATURE_FAILURE_NO_DISPLAY
[GFX1-]: Failed[3] to create EGL library  display: FEATURE_FAILURE_NO_DISPLAY
[GFX1-]: Failed GL context creation for hardware WebRender: true
[GFX1-]: Failed[3] to create EGL library  display: FEATURE_FAILURE_NO_DISPLAY
[GFX1-]: Failed[3] to create EGL library  display: FEATURE_FAILURE_NO_DISPLAY
[GFX1-]: Failed GL context creation for hardware WebRender: true
[GFX1-]: Failed[3] to create EGL library  display: FEATURE_FAILURE_NO_DISPLAY
[GFX1-]: Failed[3] to create EGL library  display: FEATURE_FAILURE_NO_DISPLAY
[GFX1-]: Failed GL context creation for hardware WebRender: true
[GFX1-]: Failed[3] to create EGL library  display: FEATURE_FAILURE_NO_DISPLAY
[GFX1-]: Failed[3] to create EGL library  display: FEATURE_FAILURE_NO_DISPLAY
[GFX1-]: Failed GL context creation for WebRender: 0
[GFX1-]: FEATURE_FAILURE_WEBRENDER_INITIALIZE_UNSPECIFIED(Create)
[GFX1-]: Failed to connect WebRenderBridgeChild. isParent=true
[GFX1-]: Fallback WR to SW-WR
```

**Comment by satmandu** [comment]
Also worth noting:
```bash
__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/10_nvidia.json eglinfo -p wayland -B
Wayland platform:
eglinfo: eglInitialize failed

eglinfo -p wayland -B
Wayland platform:
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
EGL API version: 1.5
EGL vendor string: Mesa Project
EGL version string: 1.5
EGL client APIs: OpenGL OpenGL_ES
OpenGL core profile vendor: Mesa
OpenGL core profile renderer: llvmpipe (LLVM 19.1.7, 256 bits)
OpenGL core profile version: 4.5 (Core Profile) Mesa 25.0.2-1ubuntu2
OpenGL core profile shading language version: 4.50
OpenGL compatibility profile vendor: Mesa
OpenGL compatibility profile renderer: llvmpipe (LLVM 19.1.7, 256 bits)
OpenGL compatibility profile version: 4.5 (Compatibility Profile) Mesa 25.0.2-1ubuntu2
OpenGL compatibility profile shading language version: 4.50
OpenGL ES profile vendor: Mesa
OpenGL ES profile renderer: llvmpipe (LLVM 19.1.7, 256 bits)
OpenGL ES profile version: OpenGL ES 3.2 Mesa 25.0.2-1ubuntu2
OpenGL ES profile shading language version: OpenGL ES GLSL ES 3.20
```

(nvidia driver based eglinfo is broken.)
